### ISSUE TITLE
Do not load any components before api calls are complete

### ISSUE THREAD

**Issue by Guo-William** [kimberlypn/TravelPal#25]
Do not load any components before api calls are complete!

If you attempt to before the data exists, for instance when you return to a select page like viewing a user profile, the react component will error out because some values are null.

Fix: have an isLoaded field that is only true upon api calls completion

https://github.com/Guo-William/task3/blob/master/assets/js/api.js#L6
^ example

**Comment by long74100** [comment]
Can we use component lifecycle methods for this?
