### ISSUE TITLE
Make App Mobile-Friendly

### ISSUE THREAD

**Issue by kimberlypn** [kimberlypn/TravelPal#6]
## TODO
- Make navigation bar collapsible so that it is compatible with mobile
- Fix any other styling issues to make things nice on mobile

## Maybe
- Change to side navigation bar

**Comment by Guo-William** [comment]
No need to change to side navigation at this point it looked pretty good as is. Just need to make it look nice when on Mobile or a smaller screen.

**Comment by kimberlypn** [comment]
Okay, that's fine.
